In [2]:
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go
import plotly.plotly as py
import pandas_datareader as web
import pandas as pd
import datetime as dt
import numpy as np

In [112]:
start = dt.datetime(2017, 1, 1)
end = dt.datetime(2018,10,24)

df = web.DataReader("jnug", "yahoo", start, end).reset_index()
df2 = web.DataReader("jdst", "yahoo", start, end).reset_index()
df3 = web.DataReader("nugt", "yahoo", start, end).reset_index()
df4 = web.DataReader("dust", "yahoo", start, end).reset_index()
df5 = web.DataReader("gld", "yahoo", start, end).reset_index()

print(df2.head())

opac = 0.7
trace = go.Scatter(
    name = "JNUG",
    x = df.Date,
    y = df["Adj Close"],
    line = dict(color = '#f44141'),
    opacity = opac
)

trace2 = go.Scatter(
    name = "JDST",
    x = df2.Date,
    y = df2["Adj Close"],
    line = dict(color = '#4152f4'),
    opacity = opac
)

trace3 = go.Scatter(
    name = "NUGT",
    x = df3.Date,
    y = df3["Adj Close"],
    line = dict(color = '#f49d41'),
    opacity = opac
)

trace4 = go.Scatter(
    name = "DUST",
    x = df4.Date,
    y = df4["Adj Close"],
    line = dict(color = '#a041f4'),
    opacity = opac
)

trace5 = go.Scatter(
    name = "GLD",
    x = df5.Date,
    y = df5["Adj Close"],
    line = dict(color = '#f4dc41'),
    opacity = opac
)

#.pct
#series = df.Series()
#series = df["Close"]

layout = go.Layout(
    title = "Gold ETFs from 2017 to 2018",
    yaxis = dict(title = "Price ($)")
)

data = [trace, trace2, trace3, trace4, trace5]
figure = go.Figure(data = data, layout = layout)
py.iplot(figure, filename = "gold ETFs chart")

        Date        High         Low        Open       Close      Volume  \
0 2017-01-03  138.839996  114.000000  138.080002  114.480003   5624100.0   
1 2017-01-04  117.959999  108.000000  109.199997  109.239998   6715800.0   
2 2017-01-05   99.839996   77.519997   99.000000   80.879997  13978400.0   
3 2017-01-06   99.800003   80.199997   86.919998   91.440002  16802800.0   
4 2017-01-09   90.080002   76.959999   84.120003   87.279999  13905500.0   

    Adj Close  
0  114.173164  
1  108.947205  
2   80.663216  
3   91.194916  
4   87.046059  


In [48]:
df_all = pd.DataFrame()
df_all["Date"] = df["Date"]

df_all["Close JNUG"] = df["Adj Close"]
df_all["Close JDST"] = df2["Adj Close"]
df_all["Close NUGT"] = df3["Adj Close"]
df_all["Close DUST"] = df4["Adj Close"]
df_all["Close GLD"] = df5["Adj Close"]

In [51]:
df_all_corr = df_all.corr()
print(df_all_corr.head())

            Close JNUG  Close JDST  Close NUGT  Close DUST  Close GLD
Close JNUG    1.000000    0.312162    0.977833    0.134403   0.280273
Close JDST    0.312162    1.000000    0.225463    0.939020  -0.471215
Close NUGT    0.977833    0.225463    1.000000    0.006901   0.398429
Close DUST    0.134403    0.939020    0.006901    1.000000  -0.669467
Close GLD     0.280273   -0.471215    0.398429   -0.669467   1.000000


In [57]:
print(df_all_corr["Close JNUG"]["Close JDST"])
print(df_all_corr.index)

0.31216238598832424
Index(['Close JNUG', 'Close JDST', 'Close NUGT', 'Close DUST', 'Close GLD'], dtype='object')


In [146]:
bars = go.Bar(
    name = "JNUG",
    x = ["JNUG", "JDST", "NUGT", "DUST", "GLD"],
    #y = [df_all_corr["Close JNUG"]["Close JNUG"], df_all_corr["Close JNUG"]["Close JDST"],
    #     df_all_corr["Close JNUG"]["Close NUGT"], df_all_corr["Close JNUG"]["Close DUST"],
    #     df_all_corr["Close JNUG"]["Close GLD"]],
    y = df_all_corr["Close JNUG"].values,
    marker=dict(
        color='#f44141'
    ),
    opacity = opac
)

bars2 = go.Bar(
    name = "JDST",
    x = ["JNUG", "JDST", "NUGT", "DUST", "GLD"],
    y = df_all_corr["Close JDST"].values,
    marker=dict(
        color='#4152f4'
    ),
    opacity = opac
)

bars3 = go.Bar(
    name = "NUGT",
    x = ["JNUG", "JDST", "NUGT", "DUST", "GLD"],
    y = df_all_corr["Close NUGT"].values,
    marker=dict(
        color='#f49d41'
    ),
    opacity = opac
)

bars4 = go.Bar(
    name = "DUST",
    x = ["JNUG", "JDST", "NUGT", "DUST", "GLD"],
    y = df_all_corr["Close DUST"].values,
    marker=dict(
        color='#a041f4'
    ),
    opacity = opac
)

bars5 = go.Bar(
    name = "GLD",
    x = ["JNUG", "JDST", "NUGT", "DUST", "GLD"],
    y = df_all_corr["Close GLD"].values,
    marker=dict(
        color='#f4dc41'
    ),
    opacity = opac
)

layout = go.Layout(
    title = "Percent correlation of Gold ETFs"
)
data = [bars5, bars, bars3, bars2, bars4]
figure = go.Figure(data = data, layout = layout)
py.iplot(figure, filename='grouped-bar')

In [144]:
print(df_all_corr["Close JNUG"].values)

[1.         0.31216239 0.9778334  0.13440324 0.2802729 ]


In [125]:
print(df_all_corr.values)

[[ 1.          0.31216239  0.9778334   0.13440324  0.2802729 ]
 [ 0.31216239  1.          0.22546273  0.93902049 -0.47121546]
 [ 0.9778334   0.22546273  1.          0.00690103  0.39842946]
 [ 0.13440324  0.93902049  0.00690103  1.         -0.66946737]
 [ 0.2802729  -0.47121546  0.39842946 -0.66946737  1.        ]]


df.values gives the array of everything inside of the df
df.columns gives the x axis names of everything
df.index gives the y axis names of everything

In [139]:
trace_heat = go.Heatmap(z = df_all_corr.values,
                        x = df_all_corr.columns,
                        y = df_all_corr.index,
                        colorscale='Viridis'
                       )
data=[trace_heat]
layout = go.Layout(title = "Correlation Heatmap")
figure = go.Figure(data = data, layout = layout)
py.iplot(figure, filename = 'heatmap')

In [137]:
print(df_all_corr.columns)
print(df_all_corr.index)
s = pd.Series()
s = df_all_corr.columns
print(s)

Index(['Close JNUG', 'Close JDST', 'Close NUGT', 'Close DUST', 'Close GLD'], dtype='object')
Index(['Close JNUG', 'Close JDST', 'Close NUGT', 'Close DUST', 'Close GLD'], dtype='object')
Index(['Close JNUG', 'Close JDST', 'Close NUGT', 'Close DUST', 'Close GLD'], dtype='object')


In [105]:
layout = go.Layout(
    title = "JNUG, NUGT, & GLD from 2017 to 2018",
    yaxis = dict(title = "Price ($)")
)

data = [trace, trace3, trace5]
figure = go.Figure(data = data, layout = layout)
py.iplot(figure, filename = "Gold Miners Bull ETFs")

In [111]:
#percent change
df["% Change"] =  df["Adj Close"].pct_change()

num_pos = 0
num_neg = 0
one_percent = 0
for i in df["% Change"]:
    if abs(i) <= 0.01:
        one_percent += 1
    elif i > 0:
        num_pos += 1
    elif i < 0:
        num_neg += 1
end

print(num_pos)
print(num_neg)
print(one_percent)

labels = ['Green Days','Red Days','Days with 1% change or less']
values = [num_pos, num_neg, one_percent]
colors = ["#2df226", "#ff3838", "#e0e0e0"]

trace_pie = go.Pie(
    labels=labels,
    values=values,
    marker=dict(colors=colors),
    opacity = 0.8
)
data = [trace_pie]
layout = go.Layout(title = "Green & Red Days")
figure = go.Figure(data = data, layout = layout)
py.iplot(figure, filename='pie_chart')

184
190
83


In [116]:
#df6 = pd.DataFrame() #empty df
df5["Adj Close Inverse"] = -df5["Adj Close"] + 200

trace6 = go.Scatter(
    name = "Approximate Inverse GLD",
    x = df5.Date,
    y = df5["Adj Close Inverse"],
    opacity = opac
)

layout = go.Layout(
    title = "JDST, DUST, & GLD from 2017 to 2018",
    yaxis = dict(title = "Price ($)")
)
data = [trace2, trace4, trace6]
figure = go.Figure(data = data, layout = layout)
py.iplot(figure, filename = "Gold Miners Bear ETFs")